// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class TSSCityTraffic;
@class TSSCityTraffic_Builder;
@class TSSCoordinate;
@class TSSCoordinate_Builder;
@class TSSDeviceReport;
@class TSSDeviceReport_Builder;
@class TSSLocation;
@class TSSLocation_Builder;
@class TSSPackage;
@class TSSPackage_Builder;
@class TSSRoadTraffic;
@class TSSRoadTraffic_Builder;
@class TSSRoute;
@class TSSRoute_Builder;
@class TSSSegment;
@class TSSSegmentTraffic;
@class TSSSegmentTraffic_Builder;
@class TSSSegment_Builder;
@class TSSTrafficProbe;
@class TSSTrafficProbe_Builder;
@class TSSTrafficSub;
@class TSSTrafficSub_Builder;
typedef enum {
  TSSDirectionUnknown = 0,
  TSSDirectionEast = 1,
  TSSDirectionNortheast = 2,
  TSSDirectionNorth = 3,
  TSSDirectionNorthwest = 4,
  TSSDirectionWest = 5,
  TSSDirectionSouthwest = 6,
  TSSDirectionSouth = 7,
  TSSDirectionSoutheast = 8,
} TSSDirection;

BOOL TSSDirectionIsValidValue(TSSDirection value);

typedef enum {
  TSSOprTypeSubCreate = 1,
  TSSOprTypeSubDelete = 2,
  TSSOprTypeSubUpdate = 3,
} TSSOprType;

BOOL TSSOprTypeIsValidValue(TSSOprType value);

typedef enum {
  TSSPubTypePubOnce = 1,
  TSSPubTypePubEvent = 2,
  TSSPubTypePubTimer = 3,
} TSSPubType;

BOOL TSSPubTypeIsValidValue(TSSPubType value);

typedef enum {
  TSSErrCodeVersionImcompatible = 273,
  TSSErrCodeVersionLow = 785,
  TSSErrCodeMsgDirError = 544,
  TSSErrCodeMsgTypeError = 560,
  TSSErrCodeTimeout = 848,
  TSSErrCodeOthers = 2304,
} TSSErrCode;

BOOL TSSErrCodeIsValidValue(TSSErrCode value);

typedef enum {
  TSSMsgDirClient2Tss = 1,
  TSSMsgDirTss2Client = 2,
} TSSMsgDir;

BOOL TSSMsgDirIsValidValue(TSSMsgDir value);

typedef enum {
  TSSMsgTypeVoid = 1,
  TSSMsgTypeErrCode = 2,
  TSSMsgTypeTrafficSub = 4,
  TSSMsgTypeTrafficReport = 5,
  TSSMsgTypeDeviceReport = 6,
  TSSMsgTypeCityTrafficPub = 19,
} TSSMsgType;

BOOL TSSMsgTypeIsValidValue(TSSMsgType value);


@interface TssRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface TSSCoordinate : PBGeneratedMessage {
@private
  BOOL hasLng_:1;
  BOOL hasLat_:1;
  Float64 lng;
  Float64 lat;
}
- (BOOL) hasLng;
- (BOOL) hasLat;
@property (readonly) Float64 lng;
@property (readonly) Float64 lat;

+ (TSSCoordinate*) defaultInstance;
- (TSSCoordinate*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSCoordinate_Builder*) builder;
+ (TSSCoordinate_Builder*) builder;
+ (TSSCoordinate_Builder*) builderWithPrototype:(TSSCoordinate*) prototype;

+ (TSSCoordinate*) parseFromData:(NSData*) data;
+ (TSSCoordinate*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSCoordinate*) parseFromInputStream:(NSInputStream*) input;
+ (TSSCoordinate*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSCoordinate*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSCoordinate*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSCoordinate_Builder : PBGeneratedMessage_Builder {
@private
  TSSCoordinate* result;
}

- (TSSCoordinate*) defaultInstance;

- (TSSCoordinate_Builder*) clear;
- (TSSCoordinate_Builder*) clone;

- (TSSCoordinate*) build;
- (TSSCoordinate*) buildPartial;

- (TSSCoordinate_Builder*) mergeFrom:(TSSCoordinate*) other;
- (TSSCoordinate_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSCoordinate_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLng;
- (Float64) lng;
- (TSSCoordinate_Builder*) setLng:(Float64) value;
- (TSSCoordinate_Builder*) clearLng;

- (BOOL) hasLat;
- (Float64) lat;
- (TSSCoordinate_Builder*) setLat:(Float64) value;
- (TSSCoordinate_Builder*) clearLat;
@end

@interface TSSLocation : PBGeneratedMessage {
@private
  BOOL hasLng_:1;
  BOOL hasLat_:1;
  BOOL hasName_:1;
  BOOL hasAdt_:1;
  Float64 lng;
  Float64 lat;
  NSString* name;
  NSString* adt;
}
- (BOOL) hasLng;
- (BOOL) hasLat;
- (BOOL) hasName;
- (BOOL) hasAdt;
@property (readonly) Float64 lng;
@property (readonly) Float64 lat;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* adt;

+ (TSSLocation*) defaultInstance;
- (TSSLocation*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSLocation_Builder*) builder;
+ (TSSLocation_Builder*) builder;
+ (TSSLocation_Builder*) builderWithPrototype:(TSSLocation*) prototype;

+ (TSSLocation*) parseFromData:(NSData*) data;
+ (TSSLocation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSLocation*) parseFromInputStream:(NSInputStream*) input;
+ (TSSLocation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSLocation_Builder : PBGeneratedMessage_Builder {
@private
  TSSLocation* result;
}

- (TSSLocation*) defaultInstance;

- (TSSLocation_Builder*) clear;
- (TSSLocation_Builder*) clone;

- (TSSLocation*) build;
- (TSSLocation*) buildPartial;

- (TSSLocation_Builder*) mergeFrom:(TSSLocation*) other;
- (TSSLocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSLocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLng;
- (Float64) lng;
- (TSSLocation_Builder*) setLng:(Float64) value;
- (TSSLocation_Builder*) clearLng;

- (BOOL) hasLat;
- (Float64) lat;
- (TSSLocation_Builder*) setLat:(Float64) value;
- (TSSLocation_Builder*) clearLat;

- (BOOL) hasName;
- (NSString*) name;
- (TSSLocation_Builder*) setName:(NSString*) value;
- (TSSLocation_Builder*) clearName;

- (BOOL) hasAdt;
- (NSString*) adt;
- (TSSLocation_Builder*) setAdt:(NSString*) value;
- (TSSLocation_Builder*) clearAdt;
@end

@interface TSSSegment : PBGeneratedMessage {
@private
  BOOL hasRoad_:1;
  BOOL hasStart_:1;
  BOOL hasEnd_:1;
  NSString* road;
  TSSCoordinate* start;
  TSSCoordinate* end;
}
- (BOOL) hasStart;
- (BOOL) hasEnd;
- (BOOL) hasRoad;
@property (readonly, retain) TSSCoordinate* start;
@property (readonly, retain) TSSCoordinate* end;
@property (readonly, retain) NSString* road;

+ (TSSSegment*) defaultInstance;
- (TSSSegment*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSSegment_Builder*) builder;
+ (TSSSegment_Builder*) builder;
+ (TSSSegment_Builder*) builderWithPrototype:(TSSSegment*) prototype;

+ (TSSSegment*) parseFromData:(NSData*) data;
+ (TSSSegment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSSegment*) parseFromInputStream:(NSInputStream*) input;
+ (TSSSegment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSSegment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSSegment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSSegment_Builder : PBGeneratedMessage_Builder {
@private
  TSSSegment* result;
}

- (TSSSegment*) defaultInstance;

- (TSSSegment_Builder*) clear;
- (TSSSegment_Builder*) clone;

- (TSSSegment*) build;
- (TSSSegment*) buildPartial;

- (TSSSegment_Builder*) mergeFrom:(TSSSegment*) other;
- (TSSSegment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSSegment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStart;
- (TSSCoordinate*) start;
- (TSSSegment_Builder*) setStart:(TSSCoordinate*) value;
- (TSSSegment_Builder*) setStartBuilder:(TSSCoordinate_Builder*) builderForValue;
- (TSSSegment_Builder*) mergeStart:(TSSCoordinate*) value;
- (TSSSegment_Builder*) clearStart;

- (BOOL) hasEnd;
- (TSSCoordinate*) end;
- (TSSSegment_Builder*) setEnd:(TSSCoordinate*) value;
- (TSSSegment_Builder*) setEndBuilder:(TSSCoordinate_Builder*) builderForValue;
- (TSSSegment_Builder*) mergeEnd:(TSSCoordinate*) value;
- (TSSSegment_Builder*) clearEnd;

- (BOOL) hasRoad;
- (NSString*) road;
- (TSSSegment_Builder*) setRoad:(NSString*) value;
- (TSSSegment_Builder*) clearRoad;
@end

@interface TSSRoute : PBGeneratedMessage {
@private
  BOOL hasIdentity_:1;
  int64_t identity;
  NSMutableArray* mutableSegmentsList;
}
- (BOOL) hasIdentity;
@property (readonly) int64_t identity;
- (NSArray*) segmentsList;
- (TSSSegment*) segmentsAtIndex:(int32_t) index;

+ (TSSRoute*) defaultInstance;
- (TSSRoute*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSRoute_Builder*) builder;
+ (TSSRoute_Builder*) builder;
+ (TSSRoute_Builder*) builderWithPrototype:(TSSRoute*) prototype;

+ (TSSRoute*) parseFromData:(NSData*) data;
+ (TSSRoute*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSRoute*) parseFromInputStream:(NSInputStream*) input;
+ (TSSRoute*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSRoute*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSRoute*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSRoute_Builder : PBGeneratedMessage_Builder {
@private
  TSSRoute* result;
}

- (TSSRoute*) defaultInstance;

- (TSSRoute_Builder*) clear;
- (TSSRoute_Builder*) clone;

- (TSSRoute*) build;
- (TSSRoute*) buildPartial;

- (TSSRoute_Builder*) mergeFrom:(TSSRoute*) other;
- (TSSRoute_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSRoute_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIdentity;
- (int64_t) identity;
- (TSSRoute_Builder*) setIdentity:(int64_t) value;
- (TSSRoute_Builder*) clearIdentity;

- (NSArray*) segmentsList;
- (TSSSegment*) segmentsAtIndex:(int32_t) index;
- (TSSRoute_Builder*) replaceSegmentsAtIndex:(int32_t) index with:(TSSSegment*) value;
- (TSSRoute_Builder*) addSegments:(TSSSegment*) value;
- (TSSRoute_Builder*) addAllSegments:(NSArray*) values;
- (TSSRoute_Builder*) clearSegmentsList;
@end

@interface TSSTrafficProbe : PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasSpeed_:1;
  BOOL hasAcceleration_:1;
  BOOL hasSegment_:1;
  BOOL hasLocation_:1;
  BOOL hasDirection_:1;
  int64_t timestamp;
  int32_t speed;
  int32_t acceleration;
  TSSSegment* segment;
  TSSCoordinate* location;
  TSSDirection direction;
}
- (BOOL) hasSegment;
- (BOOL) hasLocation;
- (BOOL) hasTimestamp;
- (BOOL) hasDirection;
- (BOOL) hasSpeed;
- (BOOL) hasAcceleration;
@property (readonly, retain) TSSSegment* segment;
@property (readonly, retain) TSSCoordinate* location;
@property (readonly) int64_t timestamp;
@property (readonly) TSSDirection direction;
@property (readonly) int32_t speed;
@property (readonly) int32_t acceleration;

+ (TSSTrafficProbe*) defaultInstance;
- (TSSTrafficProbe*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSTrafficProbe_Builder*) builder;
+ (TSSTrafficProbe_Builder*) builder;
+ (TSSTrafficProbe_Builder*) builderWithPrototype:(TSSTrafficProbe*) prototype;

+ (TSSTrafficProbe*) parseFromData:(NSData*) data;
+ (TSSTrafficProbe*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSTrafficProbe*) parseFromInputStream:(NSInputStream*) input;
+ (TSSTrafficProbe*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSTrafficProbe*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSTrafficProbe*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSTrafficProbe_Builder : PBGeneratedMessage_Builder {
@private
  TSSTrafficProbe* result;
}

- (TSSTrafficProbe*) defaultInstance;

- (TSSTrafficProbe_Builder*) clear;
- (TSSTrafficProbe_Builder*) clone;

- (TSSTrafficProbe*) build;
- (TSSTrafficProbe*) buildPartial;

- (TSSTrafficProbe_Builder*) mergeFrom:(TSSTrafficProbe*) other;
- (TSSTrafficProbe_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSTrafficProbe_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSegment;
- (TSSSegment*) segment;
- (TSSTrafficProbe_Builder*) setSegment:(TSSSegment*) value;
- (TSSTrafficProbe_Builder*) setSegmentBuilder:(TSSSegment_Builder*) builderForValue;
- (TSSTrafficProbe_Builder*) mergeSegment:(TSSSegment*) value;
- (TSSTrafficProbe_Builder*) clearSegment;

- (BOOL) hasLocation;
- (TSSCoordinate*) location;
- (TSSTrafficProbe_Builder*) setLocation:(TSSCoordinate*) value;
- (TSSTrafficProbe_Builder*) setLocationBuilder:(TSSCoordinate_Builder*) builderForValue;
- (TSSTrafficProbe_Builder*) mergeLocation:(TSSCoordinate*) value;
- (TSSTrafficProbe_Builder*) clearLocation;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (TSSTrafficProbe_Builder*) setTimestamp:(int64_t) value;
- (TSSTrafficProbe_Builder*) clearTimestamp;

- (BOOL) hasDirection;
- (TSSDirection) direction;
- (TSSTrafficProbe_Builder*) setDirection:(TSSDirection) value;
- (TSSTrafficProbe_Builder*) clearDirection;

- (BOOL) hasSpeed;
- (int32_t) speed;
- (TSSTrafficProbe_Builder*) setSpeed:(int32_t) value;
- (TSSTrafficProbe_Builder*) clearSpeed;

- (BOOL) hasAcceleration;
- (int32_t) acceleration;
- (TSSTrafficProbe_Builder*) setAcceleration:(int32_t) value;
- (TSSTrafficProbe_Builder*) clearAcceleration;
@end

@interface TSSSegmentTraffic : PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasSpeed_:1;
  BOOL hasDetails_:1;
  BOOL hasSegment_:1;
  BOOL hasDirection_:1;
  int64_t timestamp;
  int32_t speed;
  NSString* details;
  TSSSegment* segment;
  TSSDirection direction;
}
- (BOOL) hasSegment;
- (BOOL) hasTimestamp;
- (BOOL) hasDirection;
- (BOOL) hasSpeed;
- (BOOL) hasDetails;
@property (readonly, retain) TSSSegment* segment;
@property (readonly) int64_t timestamp;
@property (readonly) TSSDirection direction;
@property (readonly) int32_t speed;
@property (readonly, retain) NSString* details;

+ (TSSSegmentTraffic*) defaultInstance;
- (TSSSegmentTraffic*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSSegmentTraffic_Builder*) builder;
+ (TSSSegmentTraffic_Builder*) builder;
+ (TSSSegmentTraffic_Builder*) builderWithPrototype:(TSSSegmentTraffic*) prototype;

+ (TSSSegmentTraffic*) parseFromData:(NSData*) data;
+ (TSSSegmentTraffic*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSSegmentTraffic*) parseFromInputStream:(NSInputStream*) input;
+ (TSSSegmentTraffic*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSSegmentTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSSegmentTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSSegmentTraffic_Builder : PBGeneratedMessage_Builder {
@private
  TSSSegmentTraffic* result;
}

- (TSSSegmentTraffic*) defaultInstance;

- (TSSSegmentTraffic_Builder*) clear;
- (TSSSegmentTraffic_Builder*) clone;

- (TSSSegmentTraffic*) build;
- (TSSSegmentTraffic*) buildPartial;

- (TSSSegmentTraffic_Builder*) mergeFrom:(TSSSegmentTraffic*) other;
- (TSSSegmentTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSSegmentTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSegment;
- (TSSSegment*) segment;
- (TSSSegmentTraffic_Builder*) setSegment:(TSSSegment*) value;
- (TSSSegmentTraffic_Builder*) setSegmentBuilder:(TSSSegment_Builder*) builderForValue;
- (TSSSegmentTraffic_Builder*) mergeSegment:(TSSSegment*) value;
- (TSSSegmentTraffic_Builder*) clearSegment;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (TSSSegmentTraffic_Builder*) setTimestamp:(int64_t) value;
- (TSSSegmentTraffic_Builder*) clearTimestamp;

- (BOOL) hasDirection;
- (TSSDirection) direction;
- (TSSSegmentTraffic_Builder*) setDirection:(TSSDirection) value;
- (TSSSegmentTraffic_Builder*) clearDirection;

- (BOOL) hasSpeed;
- (int32_t) speed;
- (TSSSegmentTraffic_Builder*) setSpeed:(int32_t) value;
- (TSSSegmentTraffic_Builder*) clearSpeed;

- (BOOL) hasDetails;
- (NSString*) details;
- (TSSSegmentTraffic_Builder*) setDetails:(NSString*) value;
- (TSSSegmentTraffic_Builder*) clearDetails;
@end

@interface TSSRoadTraffic : PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasRoad_:1;
  BOOL hasHref_:1;
  BOOL hasDesc_:1;
  int64_t timestamp;
  NSString* road;
  NSString* href;
  NSString* desc;
  NSMutableArray* mutableSegmentTrafficsList;
}
- (BOOL) hasRoad;
- (BOOL) hasTimestamp;
- (BOOL) hasHref;
- (BOOL) hasDesc;
@property (readonly, retain) NSString* road;
@property (readonly) int64_t timestamp;
@property (readonly, retain) NSString* href;
@property (readonly, retain) NSString* desc;
- (NSArray*) segmentTrafficsList;
- (TSSSegmentTraffic*) segmentTrafficsAtIndex:(int32_t) index;

+ (TSSRoadTraffic*) defaultInstance;
- (TSSRoadTraffic*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSRoadTraffic_Builder*) builder;
+ (TSSRoadTraffic_Builder*) builder;
+ (TSSRoadTraffic_Builder*) builderWithPrototype:(TSSRoadTraffic*) prototype;

+ (TSSRoadTraffic*) parseFromData:(NSData*) data;
+ (TSSRoadTraffic*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSRoadTraffic*) parseFromInputStream:(NSInputStream*) input;
+ (TSSRoadTraffic*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSRoadTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSRoadTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSRoadTraffic_Builder : PBGeneratedMessage_Builder {
@private
  TSSRoadTraffic* result;
}

- (TSSRoadTraffic*) defaultInstance;

- (TSSRoadTraffic_Builder*) clear;
- (TSSRoadTraffic_Builder*) clone;

- (TSSRoadTraffic*) build;
- (TSSRoadTraffic*) buildPartial;

- (TSSRoadTraffic_Builder*) mergeFrom:(TSSRoadTraffic*) other;
- (TSSRoadTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSRoadTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRoad;
- (NSString*) road;
- (TSSRoadTraffic_Builder*) setRoad:(NSString*) value;
- (TSSRoadTraffic_Builder*) clearRoad;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (TSSRoadTraffic_Builder*) setTimestamp:(int64_t) value;
- (TSSRoadTraffic_Builder*) clearTimestamp;

- (NSArray*) segmentTrafficsList;
- (TSSSegmentTraffic*) segmentTrafficsAtIndex:(int32_t) index;
- (TSSRoadTraffic_Builder*) replaceSegmentTrafficsAtIndex:(int32_t) index with:(TSSSegmentTraffic*) value;
- (TSSRoadTraffic_Builder*) addSegmentTraffics:(TSSSegmentTraffic*) value;
- (TSSRoadTraffic_Builder*) addAllSegmentTraffics:(NSArray*) values;
- (TSSRoadTraffic_Builder*) clearSegmentTrafficsList;

- (BOOL) hasHref;
- (NSString*) href;
- (TSSRoadTraffic_Builder*) setHref:(NSString*) value;
- (TSSRoadTraffic_Builder*) clearHref;

- (BOOL) hasDesc;
- (NSString*) desc;
- (TSSRoadTraffic_Builder*) setDesc:(NSString*) value;
- (TSSRoadTraffic_Builder*) clearDesc;
@end

@interface TSSCityTraffic : PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasCity_:1;
  int64_t timestamp;
  NSString* city;
  NSMutableArray* mutableRoadTrafficsList;
}
- (BOOL) hasCity;
- (BOOL) hasTimestamp;
@property (readonly, retain) NSString* city;
@property (readonly) int64_t timestamp;
- (NSArray*) roadTrafficsList;
- (TSSRoadTraffic*) roadTrafficsAtIndex:(int32_t) index;

+ (TSSCityTraffic*) defaultInstance;
- (TSSCityTraffic*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSCityTraffic_Builder*) builder;
+ (TSSCityTraffic_Builder*) builder;
+ (TSSCityTraffic_Builder*) builderWithPrototype:(TSSCityTraffic*) prototype;

+ (TSSCityTraffic*) parseFromData:(NSData*) data;
+ (TSSCityTraffic*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSCityTraffic*) parseFromInputStream:(NSInputStream*) input;
+ (TSSCityTraffic*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSCityTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSCityTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSCityTraffic_Builder : PBGeneratedMessage_Builder {
@private
  TSSCityTraffic* result;
}

- (TSSCityTraffic*) defaultInstance;

- (TSSCityTraffic_Builder*) clear;
- (TSSCityTraffic_Builder*) clone;

- (TSSCityTraffic*) build;
- (TSSCityTraffic*) buildPartial;

- (TSSCityTraffic_Builder*) mergeFrom:(TSSCityTraffic*) other;
- (TSSCityTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSCityTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCity;
- (NSString*) city;
- (TSSCityTraffic_Builder*) setCity:(NSString*) value;
- (TSSCityTraffic_Builder*) clearCity;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (TSSCityTraffic_Builder*) setTimestamp:(int64_t) value;
- (TSSCityTraffic_Builder*) clearTimestamp;

- (NSArray*) roadTrafficsList;
- (TSSRoadTraffic*) roadTrafficsAtIndex:(int32_t) index;
- (TSSCityTraffic_Builder*) replaceRoadTrafficsAtIndex:(int32_t) index with:(TSSRoadTraffic*) value;
- (TSSCityTraffic_Builder*) addRoadTraffics:(TSSRoadTraffic*) value;
- (TSSCityTraffic_Builder*) addAllRoadTraffics:(NSArray*) values;
- (TSSCityTraffic_Builder*) clearRoadTrafficsList;
@end

@interface TSSTrafficSub : PBGeneratedMessage {
@private
  BOOL hasExpires_:1;
  BOOL hasCity_:1;
  BOOL hasRoute_:1;
  BOOL hasOprType_:1;
  BOOL hasPubType_:1;
  int32_t expires;
  NSString* city;
  TSSRoute* route;
  TSSOprType oprType;
  TSSPubType pubType;
}
- (BOOL) hasCity;
- (BOOL) hasRoute;
- (BOOL) hasOprType;
- (BOOL) hasPubType;
- (BOOL) hasExpires;
@property (readonly, retain) NSString* city;
@property (readonly, retain) TSSRoute* route;
@property (readonly) TSSOprType oprType;
@property (readonly) TSSPubType pubType;
@property (readonly) int32_t expires;

+ (TSSTrafficSub*) defaultInstance;
- (TSSTrafficSub*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSTrafficSub_Builder*) builder;
+ (TSSTrafficSub_Builder*) builder;
+ (TSSTrafficSub_Builder*) builderWithPrototype:(TSSTrafficSub*) prototype;

+ (TSSTrafficSub*) parseFromData:(NSData*) data;
+ (TSSTrafficSub*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSTrafficSub*) parseFromInputStream:(NSInputStream*) input;
+ (TSSTrafficSub*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSTrafficSub*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSTrafficSub*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSTrafficSub_Builder : PBGeneratedMessage_Builder {
@private
  TSSTrafficSub* result;
}

- (TSSTrafficSub*) defaultInstance;

- (TSSTrafficSub_Builder*) clear;
- (TSSTrafficSub_Builder*) clone;

- (TSSTrafficSub*) build;
- (TSSTrafficSub*) buildPartial;

- (TSSTrafficSub_Builder*) mergeFrom:(TSSTrafficSub*) other;
- (TSSTrafficSub_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSTrafficSub_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCity;
- (NSString*) city;
- (TSSTrafficSub_Builder*) setCity:(NSString*) value;
- (TSSTrafficSub_Builder*) clearCity;

- (BOOL) hasRoute;
- (TSSRoute*) route;
- (TSSTrafficSub_Builder*) setRoute:(TSSRoute*) value;
- (TSSTrafficSub_Builder*) setRouteBuilder:(TSSRoute_Builder*) builderForValue;
- (TSSTrafficSub_Builder*) mergeRoute:(TSSRoute*) value;
- (TSSTrafficSub_Builder*) clearRoute;

- (BOOL) hasOprType;
- (TSSOprType) oprType;
- (TSSTrafficSub_Builder*) setOprType:(TSSOprType) value;
- (TSSTrafficSub_Builder*) clearOprType;

- (BOOL) hasPubType;
- (TSSPubType) pubType;
- (TSSTrafficSub_Builder*) setPubType:(TSSPubType) value;
- (TSSTrafficSub_Builder*) clearPubType;

- (BOOL) hasExpires;
- (int32_t) expires;
- (TSSTrafficSub_Builder*) setExpires:(int32_t) value;
- (TSSTrafficSub_Builder*) clearExpires;
@end

@interface TSSDeviceReport : PBGeneratedMessage {
@private
  BOOL hasDeviceId_:1;
  BOOL hasDeviceName_:1;
  BOOL hasDeviceModel_:1;
  BOOL hasDeviceOsVersion_:1;
  BOOL hasDeviceToken_:1;
  NSString* deviceId;
  NSString* deviceName;
  NSString* deviceModel;
  NSString* deviceOsVersion;
  NSData* deviceToken;
}
- (BOOL) hasDeviceId;
- (BOOL) hasDeviceToken;
- (BOOL) hasDeviceName;
- (BOOL) hasDeviceModel;
- (BOOL) hasDeviceOsVersion;
@property (readonly, retain) NSString* deviceId;
@property (readonly, retain) NSData* deviceToken;
@property (readonly, retain) NSString* deviceName;
@property (readonly, retain) NSString* deviceModel;
@property (readonly, retain) NSString* deviceOsVersion;

+ (TSSDeviceReport*) defaultInstance;
- (TSSDeviceReport*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSDeviceReport_Builder*) builder;
+ (TSSDeviceReport_Builder*) builder;
+ (TSSDeviceReport_Builder*) builderWithPrototype:(TSSDeviceReport*) prototype;

+ (TSSDeviceReport*) parseFromData:(NSData*) data;
+ (TSSDeviceReport*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSDeviceReport*) parseFromInputStream:(NSInputStream*) input;
+ (TSSDeviceReport*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSDeviceReport*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSDeviceReport*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSDeviceReport_Builder : PBGeneratedMessage_Builder {
@private
  TSSDeviceReport* result;
}

- (TSSDeviceReport*) defaultInstance;

- (TSSDeviceReport_Builder*) clear;
- (TSSDeviceReport_Builder*) clone;

- (TSSDeviceReport*) build;
- (TSSDeviceReport*) buildPartial;

- (TSSDeviceReport_Builder*) mergeFrom:(TSSDeviceReport*) other;
- (TSSDeviceReport_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSDeviceReport_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeviceId;
- (NSString*) deviceId;
- (TSSDeviceReport_Builder*) setDeviceId:(NSString*) value;
- (TSSDeviceReport_Builder*) clearDeviceId;

- (BOOL) hasDeviceToken;
- (NSData*) deviceToken;
- (TSSDeviceReport_Builder*) setDeviceToken:(NSData*) value;
- (TSSDeviceReport_Builder*) clearDeviceToken;

- (BOOL) hasDeviceName;
- (NSString*) deviceName;
- (TSSDeviceReport_Builder*) setDeviceName:(NSString*) value;
- (TSSDeviceReport_Builder*) clearDeviceName;

- (BOOL) hasDeviceModel;
- (NSString*) deviceModel;
- (TSSDeviceReport_Builder*) setDeviceModel:(NSString*) value;
- (TSSDeviceReport_Builder*) clearDeviceModel;

- (BOOL) hasDeviceOsVersion;
- (NSString*) deviceOsVersion;
- (TSSDeviceReport_Builder*) setDeviceOsVersion:(NSString*) value;
- (TSSDeviceReport_Builder*) clearDeviceOsVersion;
@end

@interface TSSPackage : PBExtendableMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasVersion_:1;
  BOOL hasMsgId_:1;
  BOOL hasExpires_:1;
  BOOL hasTrafficProbe_:1;
  BOOL hasCityTraffic_:1;
  BOOL hasRoadTraffic_:1;
  BOOL hasSegmentTraffic_:1;
  BOOL hasTrafficSub_:1;
  BOOL hasRoute_:1;
  BOOL hasSegment_:1;
  BOOL hasLocation_:1;
  BOOL hasDeviceReport_:1;
  BOOL hasUserToken_:1;
  BOOL hasErrCode_:1;
  BOOL hasMsgType_:1;
  BOOL hasMsgDir_:1;
  int64_t timestamp;
  int32_t version;
  int32_t msgId;
  int32_t expires;
  TSSTrafficProbe* trafficProbe;
  TSSCityTraffic* cityTraffic;
  TSSRoadTraffic* roadTraffic;
  TSSSegmentTraffic* segmentTraffic;
  TSSTrafficSub* trafficSub;
  TSSRoute* route;
  TSSSegment* segment;
  TSSLocation* location;
  TSSDeviceReport* deviceReport;
  NSData* userToken;
  TSSErrCode errCode;
  TSSMsgType msgType;
  TSSMsgDir msgDir;
}
- (BOOL) hasVersion;
- (BOOL) hasMsgDir;
- (BOOL) hasMsgType;
- (BOOL) hasMsgId;
- (BOOL) hasTimestamp;
- (BOOL) hasExpires;
- (BOOL) hasUserToken;
- (BOOL) hasErrCode;
- (BOOL) hasDeviceReport;
- (BOOL) hasLocation;
- (BOOL) hasSegment;
- (BOOL) hasRoute;
- (BOOL) hasTrafficSub;
- (BOOL) hasSegmentTraffic;
- (BOOL) hasRoadTraffic;
- (BOOL) hasCityTraffic;
- (BOOL) hasTrafficProbe;
@property (readonly) int32_t version;
@property (readonly) TSSMsgDir msgDir;
@property (readonly) TSSMsgType msgType;
@property (readonly) int32_t msgId;
@property (readonly) int64_t timestamp;
@property (readonly) int32_t expires;
@property (readonly, retain) NSData* userToken;
@property (readonly) TSSErrCode errCode;
@property (readonly, retain) TSSDeviceReport* deviceReport;
@property (readonly, retain) TSSLocation* location;
@property (readonly, retain) TSSSegment* segment;
@property (readonly, retain) TSSRoute* route;
@property (readonly, retain) TSSTrafficSub* trafficSub;
@property (readonly, retain) TSSSegmentTraffic* segmentTraffic;
@property (readonly, retain) TSSRoadTraffic* roadTraffic;
@property (readonly, retain) TSSCityTraffic* cityTraffic;
@property (readonly, retain) TSSTrafficProbe* trafficProbe;

+ (TSSPackage*) defaultInstance;
- (TSSPackage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TSSPackage_Builder*) builder;
+ (TSSPackage_Builder*) builder;
+ (TSSPackage_Builder*) builderWithPrototype:(TSSPackage*) prototype;

+ (TSSPackage*) parseFromData:(NSData*) data;
+ (TSSPackage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSPackage*) parseFromInputStream:(NSInputStream*) input;
+ (TSSPackage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TSSPackage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TSSPackage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TSSPackage_Builder : PBExtendableMessage_Builder {
@private
  TSSPackage* result;
}

- (TSSPackage*) defaultInstance;

- (TSSPackage_Builder*) clear;
- (TSSPackage_Builder*) clone;

- (TSSPackage*) build;
- (TSSPackage*) buildPartial;

- (TSSPackage_Builder*) mergeFrom:(TSSPackage*) other;
- (TSSPackage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TSSPackage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (int32_t) version;
- (TSSPackage_Builder*) setVersion:(int32_t) value;
- (TSSPackage_Builder*) clearVersion;

- (BOOL) hasMsgDir;
- (TSSMsgDir) msgDir;
- (TSSPackage_Builder*) setMsgDir:(TSSMsgDir) value;
- (TSSPackage_Builder*) clearMsgDir;

- (BOOL) hasMsgType;
- (TSSMsgType) msgType;
- (TSSPackage_Builder*) setMsgType:(TSSMsgType) value;
- (TSSPackage_Builder*) clearMsgType;

- (BOOL) hasMsgId;
- (int32_t) msgId;
- (TSSPackage_Builder*) setMsgId:(int32_t) value;
- (TSSPackage_Builder*) clearMsgId;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (TSSPackage_Builder*) setTimestamp:(int64_t) value;
- (TSSPackage_Builder*) clearTimestamp;

- (BOOL) hasExpires;
- (int32_t) expires;
- (TSSPackage_Builder*) setExpires:(int32_t) value;
- (TSSPackage_Builder*) clearExpires;

- (BOOL) hasUserToken;
- (NSData*) userToken;
- (TSSPackage_Builder*) setUserToken:(NSData*) value;
- (TSSPackage_Builder*) clearUserToken;

- (BOOL) hasErrCode;
- (TSSErrCode) errCode;
- (TSSPackage_Builder*) setErrCode:(TSSErrCode) value;
- (TSSPackage_Builder*) clearErrCode;

- (BOOL) hasDeviceReport;
- (TSSDeviceReport*) deviceReport;
- (TSSPackage_Builder*) setDeviceReport:(TSSDeviceReport*) value;
- (TSSPackage_Builder*) setDeviceReportBuilder:(TSSDeviceReport_Builder*) builderForValue;
- (TSSPackage_Builder*) mergeDeviceReport:(TSSDeviceReport*) value;
- (TSSPackage_Builder*) clearDeviceReport;

- (BOOL) hasLocation;
- (TSSLocation*) location;
- (TSSPackage_Builder*) setLocation:(TSSLocation*) value;
- (TSSPackage_Builder*) setLocationBuilder:(TSSLocation_Builder*) builderForValue;
- (TSSPackage_Builder*) mergeLocation:(TSSLocation*) value;
- (TSSPackage_Builder*) clearLocation;

- (BOOL) hasSegment;
- (TSSSegment*) segment;
- (TSSPackage_Builder*) setSegment:(TSSSegment*) value;
- (TSSPackage_Builder*) setSegmentBuilder:(TSSSegment_Builder*) builderForValue;
- (TSSPackage_Builder*) mergeSegment:(TSSSegment*) value;
- (TSSPackage_Builder*) clearSegment;

- (BOOL) hasRoute;
- (TSSRoute*) route;
- (TSSPackage_Builder*) setRoute:(TSSRoute*) value;
- (TSSPackage_Builder*) setRouteBuilder:(TSSRoute_Builder*) builderForValue;
- (TSSPackage_Builder*) mergeRoute:(TSSRoute*) value;
- (TSSPackage_Builder*) clearRoute;

- (BOOL) hasTrafficSub;
- (TSSTrafficSub*) trafficSub;
- (TSSPackage_Builder*) setTrafficSub:(TSSTrafficSub*) value;
- (TSSPackage_Builder*) setTrafficSubBuilder:(TSSTrafficSub_Builder*) builderForValue;
- (TSSPackage_Builder*) mergeTrafficSub:(TSSTrafficSub*) value;
- (TSSPackage_Builder*) clearTrafficSub;

- (BOOL) hasSegmentTraffic;
- (TSSSegmentTraffic*) segmentTraffic;
- (TSSPackage_Builder*) setSegmentTraffic:(TSSSegmentTraffic*) value;
- (TSSPackage_Builder*) setSegmentTrafficBuilder:(TSSSegmentTraffic_Builder*) builderForValue;
- (TSSPackage_Builder*) mergeSegmentTraffic:(TSSSegmentTraffic*) value;
- (TSSPackage_Builder*) clearSegmentTraffic;

- (BOOL) hasRoadTraffic;
- (TSSRoadTraffic*) roadTraffic;
- (TSSPackage_Builder*) setRoadTraffic:(TSSRoadTraffic*) value;
- (TSSPackage_Builder*) setRoadTrafficBuilder:(TSSRoadTraffic_Builder*) builderForValue;
- (TSSPackage_Builder*) mergeRoadTraffic:(TSSRoadTraffic*) value;
- (TSSPackage_Builder*) clearRoadTraffic;

- (BOOL) hasCityTraffic;
- (TSSCityTraffic*) cityTraffic;
- (TSSPackage_Builder*) setCityTraffic:(TSSCityTraffic*) value;
- (TSSPackage_Builder*) setCityTrafficBuilder:(TSSCityTraffic_Builder*) builderForValue;
- (TSSPackage_Builder*) mergeCityTraffic:(TSSCityTraffic*) value;
- (TSSPackage_Builder*) clearCityTraffic;

- (BOOL) hasTrafficProbe;
- (TSSTrafficProbe*) trafficProbe;
- (TSSPackage_Builder*) setTrafficProbe:(TSSTrafficProbe*) value;
- (TSSPackage_Builder*) setTrafficProbeBuilder:(TSSTrafficProbe_Builder*) builderForValue;
- (TSSPackage_Builder*) mergeTrafficProbe:(TSSTrafficProbe*) value;
- (TSSPackage_Builder*) clearTrafficProbe;
@end

